apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cool-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cool-service
  template:
    metadata:
      labels:
        app: my-cool-service
    spec:
      containers:
        - name: my-cool-service-container
          image: kaydemir309/my-cool-service:1.0
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: my-cool-service
spec:
  type: NodePort
  selector:
    app: my-cool-service
  ports:
    - name: my-cool-service-port
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000